on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Hello world action step
      id: hello
      uses: lendingfront/python/formatter-check@main
      with:
        branch: 'main'

